# Base image
FROM python:3.11

# Install Redis Server
RUN apt-get update && apt-get install -y redis-server

# Set working directory
WORKDIR /app

# Copy files
COPY . /app

# Install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 6379 8000

# Define entrypoint
CMD ["bash", "-c", "redis-server & sleep 5 && python main.py"]
