# Default values for finpilot-chart.
# 이 파일은 템플릿에 전달할 변수들을 정의합니다.

replicaCount: 3  # 고가용성을 위한 3개의 replica

image:
  repository: "greatsangho/finpilot-app"  # 사용할 애플리케이션 이미지
  pullPolicy: IfNotPresent
  tag: "latest"  # 사용할 이미지 태그

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: LoadBalancer  # 외부 접근을 위해 LoadBalancer로 설정
  port: 80           # 서비스 포트 (Ingress가 연결할 포트)

ingress:
  enabled: true       # Ingress 활성화
  className: "nginx"  # 사용할 Ingress 클래스
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging" # "letsencrypt-prod"  # cert-manager ClusterIssuer 이름 (테스트 시는 staging 사용 가능)
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: "finpilot.duckdns.org"  # 도메인 이름을 실제 사용하는 값으로 업데이트
      paths:
        - path: "/"
          pathType: ImplementationSpecific
  tls:
    - secretName: "finpilot-tls"  # TLS 인증서가 저장될 Secret 이름
      hosts:
        - "finpilot.duckdns.org"

resources: {}

livenessProbe:
  httpGet:
    path: "/"
    port: 80
readinessProbe:
  httpGet:
    path: "/"
    port: 80

autoscaling:
  enabled: true  # 오토스케일링 활성화
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}
